name: Deploy to CapRover

on:
  push:
    branches:
      - main  # Altere para a branch desejada.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout mais recente

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy to CapRover
        run: |
          npm install -g caprover
          echo "{\"caproverUrl\": \"http://whaticket.cap.digitalis.marketing\", \"caproverApp\": \"whaticket\", \"caproverPassword\": \"${{ secrets.CAPROVER_TOKEN }}\"}" > ~/.caprover/config.json
          caprover deploy
